//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectarDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public int ID { get; set; }
        public string bar_code { get; set; }
        public string foto_path { get; set; }
        public string descripcion { get; set; }
        public string marca { get; set; }
        public string contenido { get; set; }
        public string color { get; set; }
        public string tamanio { get; set; }
    }
}
